name = "100kdo-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "100kdo-db"
database_id = "415d213a-f889-4166-8efc-eecda88fafdc"

[env.production]
name = "100kdo-api-production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "100kdo-db"
database_id = "415d213a-f889-4166-8efc-eecda88fafdc"

[vars]
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"
ALLOWED_ORIGINS = "https://100kdo.ccwu.cc,https://100kdo.com,http://localhost:3000,http://localhost:4173"
